/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DotGrid: typeof import('./../components/DotGrid.vue')['default']
    IconLucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    IconLucideDog: typeof import('~icons/lucide/dog')['default']
    IconLucideExternalLink: typeof import('~icons/lucide/external-link')['default']
    IconLucideGithub: typeof import('~icons/lucide/github')['default']
    IconLucideLanguages: typeof import('~icons/lucide/languages')['default']
    IconLucideMail: typeof import('~icons/lucide/mail')['default']
    IconLucideMoon: typeof import('~icons/lucide/moon')['default']
    IconLucidePalette: typeof import('~icons/lucide/palette')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    Shuffle: typeof import('./../components/Shuffle.vue')['default']
  }
}
